/*
 * ctgui.java
 *
 * Created on 17 juin 2008, 16:27
 */



/**
 *
 * @author  USER
 */
public class ctgui extends javax.swing.JFrame {
    
    /** Creates new form ctgui */
    public ctgui() {
       
         forbg toto=new forbg();
         setContentPane(toto);
        initComponents();
         
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.*/
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contains_table = new javax.swing.JPanel();
        tabletitle = new javax.swing.JLabel();
        contains_buttons = new javax.swing.JPanel();
        allcontracts = new javax.swing.JLabel();
        which_cont = new javax.swing.JComboBox();
        endcontracts = new javax.swing.JLabel();
        which_end_cont = new javax.swing.JComboBox();
        matric_torenew = new javax.swing.JLabel();
        enter_to_renew = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contains_table.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout contains_tableLayout = new javax.swing.GroupLayout(contains_table);
        contains_table.setLayout(contains_tableLayout);
        contains_tableLayout.setHorizontalGroup(
            contains_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        contains_tableLayout.setVerticalGroup(
            contains_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        tabletitle.setBackground(new java.awt.Color(204, 255, 51));
        tabletitle.setOpaque(true);

        contains_buttons.setBackground(new java.awt.Color(51, 255, 153));

        allcontracts.setFont(new java.awt.Font("Arial", 1, 11));
        allcontracts.setText("Tous les contrats : ");

        which_cont.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Periode d'essai", "Periode d'essai renouvellée", "CDD", "CDDR1", "CDDR2" }));

        endcontracts.setFont(new java.awt.Font("Arial", 1, 11));
        endcontracts.setText("Contrats en fin de validité ( dans 3 jours) : ");

        which_end_cont.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Periode d'essai", "Periode d'essai renouvellée", "CDD", "CDD1", "CDD2" }));

        matric_torenew.setFont(new java.awt.Font("Arial", 1, 11));
        matric_torenew.setText("Matricule : ");

        jButton1.setText("Renouveller contrat");

        javax.swing.GroupLayout contains_buttonsLayout = new javax.swing.GroupLayout(contains_buttons);
        contains_buttons.setLayout(contains_buttonsLayout);
        contains_buttonsLayout.setHorizontalGroup(
            contains_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contains_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contains_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contains_buttonsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endcontracts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(which_end_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(matric_torenew)
                        .addGap(8, 8, 8)
                        .addComponent(enter_to_renew, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contains_buttonsLayout.createSequentialGroup()
                        .addComponent(allcontracts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(which_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        contains_buttonsLayout.setVerticalGroup(
            contains_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contains_buttonsLayout.createSequentialGroup()
                .addGroup(contains_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contains_buttonsLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(contains_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allcontracts)
                            .addComponent(which_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(contains_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(which_end_cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endcontracts))
                        .addGap(13, 13, 13))
                    .addGroup(contains_buttonsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(contains_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enter_to_renew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matric_torenew))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(contains_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(tabletitle, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(contains_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(tabletitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contains_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contains_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ctgui().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allcontracts;
    private javax.swing.JPanel contains_buttons;
    private javax.swing.JPanel contains_table;
    private javax.swing.JLabel endcontracts;
    private javax.swing.JTextField enter_to_renew;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel matric_torenew;
    private javax.swing.JLabel tabletitle;
    private javax.swing.JComboBox which_cont;
    private javax.swing.JComboBox which_end_cont;
    // End of variables declaration//GEN-END:variables
    
}
